services:
  hhvm:
    container_name: theodore-lecof-router-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: .
        target: /mnt/project
    ports:
      - 8085:80
      - 48544:10641
